### ISSUE TITLE
Make the alignment better, make it tabular 

### ISSUE THREAD

**Issue by kris905** [rohanreji93/BansalApp#3]
![screen shot 2015-07-05 at 5 09 39 pm](https://cloud.githubusercontent.com/assets/3480243/8512197/abbb9576-2355-11e5-8185-13969bafe754.png)

This has to look like in the wireframe

**Comment by rohanreji93** [comment]
![screenshot from 2015-07-07 15 44 17](https://cloud.githubusercontent.com/assets/5115004/8544039/5bd5a91e-24bf-11e5-91b4-62def3b3f420.png)

changed all the sidebar and added the quick links
